### ISSUE TITLE
Tiny Progressions scythe seeds dupe bug!

### ISSUE THREAD

**Issue by knoxhack** [BlakeBr0/MysticalAgradditions#12]
It dupes Mystical Agradditions Seed.
When seeds are planted you can right click them right away and dupe unlimited seeds.
Screenshots:
http://imgur.com/gJlMa95

Mods Involved:
https://minecraft.curseforge.com/projects/tiny-progressions
https://minecraft.curseforge.com/projects/mystical-agradditions
https://minecraft.curseforge.com/projects/mystical-agriculture

**Comment by knoxhack** [comment]
https://github.com/NFINIT-Development/GalacticEngineers/issues/11

**Comment by BlakeBr0** [comment]
The tiny progressions scythes are coded to break the block then place a brand new one, which makes it so you get 1 seed, 1 essence, and 1 crop block per harvest.
In other words it's not my fault.

**Comment by BlakeBr0** [comment]
Looking at the code for their scythe again I see where the problem is. They're checking if IGrowable.canGrow is false to see if it should harvest, which I personally wouldnt say is the best way to go about it. I would assume you dont have a nether star crux under that crop, so canGrow will always return false.

**Comment by knoxhack** [comment]
Thanks for looking into this, I reported it to the Tiny Progressions author, hopefully he reply soon.
