### ISSUE TITLE
[Suggestion] Tier 6 seeds 

### ISSUE THREAD

**Issue by TokkenGmr** [BlakeBr0/MysticalAgradditions#20]
I was thinking of a couple of other items that could qualify to be tier 6 crops in 1.11/1.12 maybe even 1.10 if you are still doing 1.10

Neutronium seed - yields Pile of Neutrons from Avaritia
Gaia Spirit  seed - yields Gaia Spirit from Botania
Evil Infused Seed - yields Evil Infused Iron from ExtraUtils 2

**Comment by Colton-Slayden** [comment]
To addon to this have it somewhere in the config to add a second seed drop chance

**Comment by Willy347** [comment]
yes please add Gaia spirit seeds as it is impossible to automate otherwise.
Iknow it is intended to be that way in botania but that doesn't take away the fact that some modpacks want to include this mod to automate it.

 I'm currently playing ATM3 and on a quest to automate ATM stars. i'm getting pretty far but gaia automation just isn't possible yet :/

**Comment by BlakeBr0** [comment]
Ignoring the fact it's been 5 years since this issue was made I'll update how things are going:
- Neutronium seed: I believe I added this in the 1.12 version, 1.19 is WIP (https://github.com/BlakeBr0/MysticalAgradditions/pull/92)
- Gaia Spirit seed: 1.19 is WIP (https://github.com/BlakeBr0/MysticalAgradditions/pull/91)
- Evil Infused seed: Won't be happening since Extra Utilities is no longer being updated
