### ISSUE TITLE
[Suggestion] Tier 6 chaos shard seed

### ISSUE THREAD

**Issue by ThatGravyboat** [BlakeBr0/MysticalAgradditions#30]
Can there be a tier 6 chaos seed that give the smallest version of the chaos shards from Draconic Evolution.

**Comment by BlakeBr0** [comment]
I don't want to add seeds for items that are essentially at the tippy top of the progression tree. I feel like there needs to be things that can't just be infinitely produced automatically. In newer versions there is [Mystical Customization](https://www.curseforge.com/minecraft/mc-mods/mystical-customization) which you can use to add your own crops, so that's an option you have.
