### ISSUE TITLE
Tier 6 (or 7?) seeds 

### ISSUE THREAD

**Issue by Taccio33** [BlakeBr0/MysticalAgradditions#42]
Can you consider adding an infinity seed from avaritia. Probably configurable in the configs because it would be op. But like fluid cows now have it.. so why not

**Comment by niklas2233** [comment]
+1

**Comment by BlakeBr0** [comment]
I don't want to add seeds for items that are essentially at the tippy top of the progression tree. I feel like there needs to be things that can't just be infinitely produced automatically. In newer versions there is [Mystical Customization](https://www.curseforge.com/minecraft/mc-mods/mystical-customization) which you can use to add your own crops, so that's an option you have.
